import { Restroom, Cleaner, CleaningActivityLog, AuditLogEntry, Violation } from './types';

// Convert array of objects to CSV string and download
export function downloadCSV(filename: string, rows: Record<string, any>[]) {
  if (!rows || !rows.length) return;

  const headers = Object.keys(rows[0]);
  const csvContent = [
    headers.join(','),
    ...rows.map(row =>
      headers
        .map(header => {
          let val = row[header] === null || row[header] === undefined ? '' : String(row[header]);
          val = val.replace(/"/g, '""');
          if (val.includes(',') || val.includes('\n') || val.includes('"')) {
            val = `"${val}"`;
          }
          return val;
        })
        .join(',')
    )
  ].join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

// Generate Printable HTML layout for browser PDF print dialog
export function printPDFReport(title: string, htmlContent: string) {
  const printWindow = window.open('', '_blank', 'width=1000,height=800');
  if (!printWindow) return;

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title} - Airport Facility Report</title>
        <style>
          body {
            font-family: Arial, Helvetica, sans-serif;
            padding: 30px;
            color: #1e293b;
            background: #ffffff;
          }
          .header {
            border-bottom: 2px solid #0284c7;
            padding-bottom: 15px;
            margin-bottom: 25px;
            display: flex;
            justify-content: space-between;
            align-items: center;
          }
          .header h1 {
            margin: 0;
            color: #0369a1;
            font-size: 24px;
          }
          .header p {
            margin: 5px 0 0 0;
            color: #64748b;
            font-size: 13px;
          }
          .meta-bar {
            background: #f1f5f9;
            padding: 10px 15px;
            border-radius: 6px;
            margin-bottom: 20px;
            font-size: 12px;
            display: flex;
            gap: 20px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
            font-size: 12px;
          }
          th {
            background: #0284c7;
            color: #ffffff;
            text-align: left;
            padding: 10px;
            font-weight: 600;
          }
          td {
            padding: 10px;
            border-bottom: 1px solid #e2e8f0;
          }
          tr:nth-child(even) {
            background: #f8fafc;
          }
          .badge {
            display: inline-block;
            padding: 3px 8px;
            border-radius: 12px;
            font-size: 11px;
            font-weight: bold;
          }
          .badge-optimal { background: #dcfce7; color: #15803d; }
          .badge-action { background: #fef3c7; color: #b45309; }
          .badge-critical { background: #fee2e2; color: #b91c1c; }
          .footer {
            margin-top: 40px;
            border-top: 1px solid #cbd5e1;
            padding-top: 15px;
            font-size: 11px;
            color: #94a3b8;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1>Central Restroom Hygiene & Performance Report</h1>
            <p>Generated by Central LoRa Dashboard Controller Engine</p>
          </div>
          <div style="text-align: right;">
            <strong>Date:</strong> ${new Date().toLocaleDateString()}<br/>
            <strong>Time:</strong> ${new Date().toLocaleTimeString()}
          </div>
        </div>
        ${htmlContent}
        <div class="footer">
          Central Facility Management & Wireless LoRa Monitoring Infrastructure &copy; 2026 - Confidential Internal Record
        </div>
      </body>
    </html>
  `);

  printWindow.document.close();
  printWindow.focus();
  setTimeout(() => {
    printWindow.print();
  }, 400);
}
